### ISSUE TITLE
Storyplayer v2 doesn't support HTTPS requests

### ISSUE THREAD

**Issue by davidshrive** [datasift/storyplayer#135]
Any requests using the functions FromHTTP or UsingHTTP don't work when using htttpS addresses.

Always get this response when hitting our API....

{"type":1,"httpVersion":"1.1","statusCode":"400","statusMessage":"Bad Request","body":"<html>\r\n<head><title>400 The plain HTTP request was sent to HTTPS port<\/title><\/head>\r\n<body bgcolor=\"white\">\r\n","chunks":[],"frames":[],"bytesRead":351,"rawResponse":"","responsesCount":0,"errorMsgs":[],"mustClose":false,"combineChunks":true,"headers":{"Server":"nginx","Date":"Mon, 01 Dec 2014 15:31:44 GMT","Content-Type":"text\/html","Content-Length":"264","Connection":"close"}}

**Comment by stuartherbert** [comment]
Yeah, we've never supported HTTPS. I'm hoping to add support shortly.

**Comment by stuartherbert** [comment]
This was recently added to the 'develop' branch.
