### ISSUE TITLE
Test Environment Setup / Teardown Script Usage

### ISSUE THREAD

**Issue by vin-wu** [datasift/storyplayer#184]
Hello Stuart

At DataSift, we are evaluating whether to move to a later version of Storyplayer for writing new tests. Would you consider the most recent current develop branch (on Mar 18, 2016) to be stable for production use or is it a work-in-progress?

Currently, we are using the test-environments .json file to specify the target server details. In the latest version, it no longer uses a .json file for defining this configuration. Are there any guides or examples to illustrate how to use the new ...Env.php target files?

Vincent

**Comment by stuartherbert** [comment]
Hello Vincent,

The latest stable version of Storyplayer is v2.3.8. I'll be fixing any bugs that are reported in that version, but will not be adding new features it going forward.

The develop branch is going to become Storyplayer v3.0. SPv3 isn't going to be backwards-compatible. I'm still working out what the new Env.php files should look like. As soon as I have that sorted, I'll get them documented. SPv3 is going to drop support for the .json files for defining test environments, and move that back into PHP.

I'm aiming (but not promising) to have an SPv3 release candidate by the end of April, especially as I'm doing a talk on Storyplayer at the start of May, and would really like have SPv3 ready to announce by then :)

Best regards,
Stu
--

**Comment by vin-wu** [comment]
@stuartherbert / @mheap 

In which case, we will wait for a stable SPv3 release before evaluating whether to upgrade.

Could you please review a pull request on the master branch for v2.3.8 to address a bug?
https://github.com/datasift/storyplayer/pull/185/files
