### ISSUE TITLE
issue while installing storyplayer : storyplayer config file 'storyplayer.json.dist' not found or unreadable

### ISSUE THREAD

**Issue by vaghelakanak** [datasift/storyplayer#188]
Hi..
When i am trying to run this command :./vendor/bin/storyplayer install

i am getting this error : 

*** warning: storyplayer config file 'storyplayer.json.dist' not found or unreadable
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in D:\xampp-7.3.5\htdocs\dmsl-api\vendor\datasift\storyplayer\src\php\DataSift\Storyplayer\Injectables\DefaultSystemUnderTestName.php on line 63

Warning: count(): Parameter must be an array or an object that implements Countable in D:\xampp-7.3.5\htdocs\dmsl-api\vendor\datasift\storyplayer\src\php\DataSift\Storyplayer\Injectables\DefaultSystemUnderTestName.php on line 63
PHP Fatal error:  Declaration of DataSift\Storyplayer\Cli\ListSystems_Switch::process(Phix_Project\CliEngine $engine, $invokes = 1, $params = Array, $isDefaultParam = false) must be compatible with Phix_Project\CliEngine\CliSwitch::process(Phix_Project\CliEngine $engine, $invokes = 1, $params = Array, $isDefaultParam = false, $additionalContext = NULL) in D:\xampp-7.3.5\htdocs\dmsl-api\vendor\datasift\storyplayer\src\php\DataSift\Storyplayer\Cli\ListSystems\Switch.php on line 104

Fatal error: Declaration of DataSift\Storyplayer\Cli\ListSystems_Switch::process(Phix_Project\CliEngine $engine, $invokes = 1, $params = Array, $isDefaultParam = false) must be compatible with Phix_Project\CliEngine\CliSwitch::process(Phix_Project\CliEngine $engine, $invokes = 1, $params = Array, $isDefaultParam = false, $additionalContext = NULL) in D:\xampp-7.3.5\htdocs\dmsl-api\vendor\datasift\storyplayer\src\php\DataSift\Storyplayer\Cli\ListSystems\Switch.php on line 104

**Comment by vin-wu** [comment]
Storyplayer was designed to run on MacOS and Linux. Please see http://datasift.github.io/storyplayer/v2/learn/getting-setup/index.html for details.

**Comment by vaghelakanak** [comment]
ohh :(
